# Generated by Django 5.1.3 on 2024-11-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_car_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_bought',
            field=models.BooleanField(default=False),
        ),
    ]
